_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "MyPanopticFPN"
  WEIGHTS: "catalog://ImageNetPretrained/FAIR/R-101-GN"
  MASK_ON: False
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 101
    NORM: "GN"
    # DEFORM_ON_PER_STAGE: [False, True, True, True]
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 0.5
    IGNORE_VALUE: 255
    NUM_CLASSES: 4
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 11
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False

DATALOADER:
  NUM_WORKERS: 12
  FILTER_EMPTY_ANNOTATIONS: False
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: [1024, 1096, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
  MAX_SIZE_TRAIN: 3072
  MIN_SIZE_TEST: 1536
  MAX_SIZE_TEST: 3072
  RANDOM_FLIP: "none"
SOLVER:
  WARMUP_ITERS: 2500
  IMS_PER_BATCH: 4
  REFERENCE_WORLD_SIZE: 1
  BASE_LR: 0.004
  STEPS: (22500, 34000)
  MAX_ITER: 37500
  CHECKPOINT_PERIOD: 20000
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 2500
  AUG:
    FLIP: False

DATASETS:
  TRAIN: ("train-dataset",)
  TEST: ("val-dataset",)


OUTPUT_DIR: '/workspace/ai-train/outputs/tmp'
SEED: 42
