_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl"
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 1.0
    IGNORE_VALUE: 0
    NUM_CLASSES: ???
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: ???
  ROI_BOX_HEAD:
    NUM_CONV: 1
    CONV_DIM: 256
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False
DATALOADER:
  NUM_WORKERS: 8
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: [512]
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 512
  CROP:
    ENABLED: False
SOLVER:
  WARMUP_ITERS: 10000
  IMS_PER_BATCH: 4
  REFERENCE_WORLD_SIZE: 1
  BASE_LR: 0.001
  STEPS: (80000, 100000)
  MAX_ITER: 110000
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 32
  AUG:
    FLIP: False

DATASETS:
  TRAIN: ("train_dataset",)
  TEST: ("val_dataset",)


OUTPUT_DIR: '/workspace/ai-train/outputs/tmp'
SEED: 42
