MODEL:
  META_ARCHITECTURE: "RetinaNetWSemseg"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/retinanet_R_50_FPN_3x/190397829/model_final_5bd44e.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RETINANET:
    NUM_CLASSES: 11
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
    LABEL_SMOOTHING: 0.0
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 1.0
    IGNORE_VALUE: 255
    NUM_CLASSES: 4

DATALOADER:
  NUM_WORKERS: 12
  FILTER_EMPTY_ANNOTATIONS: False
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: [1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1794]
  MAX_SIZE_TRAIN: 4096
  MIN_SIZE_TEST: 1794
  MAX_SIZE_TEST: 4096
  RANDOM_FLIP: "none"
SOLVER:
  WARMUP_ITERS: 2500
  IMS_PER_BATCH: 6
  REFERENCE_WORLD_SIZE: 1
  BASE_LR: 0.001
  STEPS: (15000, 22500)
  MAX_ITER: 25000
  CHECKPOINT_PERIOD: 100000
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 2500
  AUG:
    FLIP: False

DATASETS:
  TRAIN: ("train-dataset",)
  TEST: ("val-dataset",)


OUTPUT_DIR: '/workspace/ai-train/outputs/tmp'
SEED: 42
VERSION: 2